#################################################################################
### dashboard ###################################################################
#################################################################################
#load shiny packages
library(shiny)
library(shinydashboard)
library(plotly)
library(ggplot2)
library(readxl)
library(dplyr)
library(reshape2)

### DZHW-Palette
DZHWpalette <- c("#7ab52a", # grün
                 "#605f5f", #grau
                 "#097d95", # türkis
                 "#f69f26", #orange
                # "#79a0c0", # blaugrau
                 "#0069b2")# #blau
                #"#b5163f" # rot

# set WD
path<-"..." # insert your path here
setwd(path)

#loading data and creating of subdatasets
data <- read_excel("fa_rates_table.xlsx")
data.labels = c("Research field", "Answer category", "Research is internationally",
           "Influence of academic policy", "Requirements generated by evaluations",
           "Effort for funding applying", "Competition between colleagues",
           "Necessity of acquiringfunding",
          "Thepressuretopublish",
           "Fundingopportunities",
            "Cooperationwithindustry",
           "Difficultyofappointmenttopost-docpositions",
           "Reliabilityofthescientificresults")
data_field1 <- filter(data, data$Research_field=="Humanities")
data_field1_long <- melt(data_field1, id.vars=c("Research_field", "Answer_category"))
data_field2 <- filter(data, data$Research_field=="Social Sciences")
data_field2_long <- melt(data_field2, id.vars=c("Research_field", "Answer_category"))
data_field3 <- filter(data, data$Research_field=="Life Sciences")
data_field3_long <- melt(data_field3, id.vars=c("Research_field", "Answer_category"))
data_field4 <- filter(data, data$Research_field=="Natural Sciences")
data_field4_long <- melt(data_field4, id.vars=c("Research_field", "Answer_category"))
data_field5 <- filter(data, data$Research_field=="Engineering")
data_field5_long <- melt(data_field5, id.vars=c("Research_field", "Answer_category"))

# create and fill dashboard
ui <- dashboardPage(
  dashboardHeader(title = "Field assessments"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Data", tabName = "datatable", icon = icon("table", lib = "font-awesome")),
      menuItem("All Fields", tabName = "all", icon = icon("graduation-cap", lib = "font-awesome")),
      menuItem("Humanities", tabName = "field1", icon = icon("masks-theater", lib = "font-awesome")),
      menuItem("Social Sciences", tabName = "field2", icon = icon("person", lib = "font-awesome")),
      menuItem("Life sciences", tabName = "field3", icon = icon("syringe", lib = "font-awesome")),
      menuItem("Natural Sciences", tabName = "field4", icon = icon("tree", lib = "font-awesome")),
      menuItem("Engineering", tabName = "field5", icon = icon("car-side", lib = "font-awesome"))
    )
  ),
  dashboardBody(
    tabItems(
      # first tabItem
      tabItem(tabName = "datatable", 
              tabBox(id="t1", width = 20,
                     tabPanel("Data", dataTableOutput("data_output"), icon = icon("table")) 
              )
              
      ), 
      
      # second tabItem
      tabItem("all",
                            box(
                selectInput("features", "Question/Statement:",
                            c("Research_is_internationally", "Influence_of_academic_policy",
                              "Requirements_generated_by_evaluations",
                              "Effort_for_funding_applying", "Competition_between_colleagues",
                              "Necessity_of_acquiring_funding", "The_pressure_to_publish",
                              "Funding_opportunities", "Cooperation_with_industry",
                              "Difficulty_of_appointment_to_post-doc_positions",
                              "Reliability_of_the_scientific_results")),width =4),
                     box(plotOutput("fa_block"), width = 12)
      ),
      
      # 1.Field tabItem
    tabItem("field1",
            box(
              selectInput("plot_type", "Plot type:",
                          c("Barplot", "2D Scatterplot", "3D Bubbleplot")),width =3),
            
            box(
              selectInput("features1_field1", "First dimension X:",
                          c("Research_is_internationally",
                            "Influence_of_academic_policy", "Requirements_generated_by_evaluations",
                            "Effort_for_funding_applying", "Competition_between_colleagues",
                            "Necessity_of_acquiring_funding", "The_pressure_to_publish", "Funding_opportunities",
                            "Cooperation_with_industry", "Difficulty_of_appointment_to_post-doc_positions",
                            "Reliability_of_the_scientific_results")),width =3),
            box(
              selectInput("features2_field1", "Second dimension Y:",
                          c("Research_is_internationally",
                            "Influence_of_academic_policy", "Requirements_generated_by_evaluations",
                            "Effort_for_funding_applying", "Competition_between_colleagues",
                            "Necessity_of_acquiring_funding", "The_pressure_to_publish", "Funding_opportunities",
                            "Cooperation_with_industry", "Difficulty_of_appointment_to_post-doc_positions",
                            "Reliability_of_the_scientific_results")),width =3),
            
            box(
              selectInput("features3_field1", "Third dimension Z:",
                          c("Research_is_internationally",
                            "Influence_of_academic_policy", "Requirements_generated_by_evaluations",
                            "Effort_for_funding_applying", "Competition_between_colleagues",
                            "Necessity_of_acquiring_funding", "The_pressure_to_publish", "Funding_opportunities",
                            "Cooperation_with_industry", "Difficulty_of_appointment_to_post-doc_positions",
                            "Reliability_of_the_scientific_results")),width =3),
            box(uiOutput("plot_field1"), width = 7)
              ),
    
    # 2.Field tabItem
    tabItem("field2",
            box(
              selectInput("plot_type2", "Plot type:",
                          c("Barplot", "2D Scatterplot", "3D Bubbleplot")),width =3),
            
            box(
              selectInput("features1_field2", "First dimension X:",
                          c("Research_is_internationally",
                            "Influence_of_academic_policy", "Requirements_generated_by_evaluations",
                            "Effort_for_funding_applying", "Competition_between_colleagues",
                            "Necessity_of_acquiring_funding", "The_pressure_to_publish", "Funding_opportunities",
                            "Cooperation_with_industry", "Difficulty_of_appointment_to_post-doc_positions",
                            "Reliability_of_the_scientific_results")),width =3),
            box(
              selectInput("features2_field2", "Second dimension Y:",
                          c("Research_is_internationally",
                            "Influence_of_academic_policy", "Requirements_generated_by_evaluations",
                            "Effort_for_funding_applying", "Competition_between_colleagues",
                            "Necessity_of_acquiring_funding", "The_pressure_to_publish", "Funding_opportunities",
                            "Cooperation_with_industry", "Difficulty_of_appointment_to_post-doc_positions",
                            "Reliability_of_the_scientific_results")),width =3),
            
            box(
              selectInput("features3_field2", "Third dimension Z:",
                          c("Research_is_internationally",
                            "Influence_of_academic_policy", "Requirements_generated_by_evaluations",
                            "Effort_for_funding_applying", "Competition_between_colleagues",
                            "Necessity_of_acquiring_funding", "The_pressure_to_publish", "Funding_opportunities",
                            "Cooperation_with_industry", "Difficulty_of_appointment_to_post-doc_positions",
                            "Reliability_of_the_scientific_results")),width =3),
            box(uiOutput("plot_field2"), width = 7)
    ),
   tabItem("field3",
                     box(
                       selectInput("plot_type3", "Plot type:",
                                   c("Barplot", "2D Scatterplot", "3D Bubbleplot")),width =3),
                     
                     box(
                       selectInput("features1_field3", "First dimension X:",
                                   c("Research_is_internationally",
                                     "Influence_of_academic_policy", "Requirements_generated_by_evaluations",
                                     "Effort_for_funding_applying", "Competition_between_colleagues",
                                     "Necessity_of_acquiring_funding", "The_pressure_to_publish", "Funding_opportunities",
                                     "Cooperation_with_industry", "Difficulty_of_appointment_to_post-doc_positions",
                                     "Reliability_of_the_scientific_results")),width =3),
                     box(
                       selectInput("features2_field3", "Second dimension Y:",
                                   c("Research_is_internationally",
                                     "Influence_of_academic_policy", "Requirements_generated_by_evaluations",
                                     "Effort_for_funding_applying", "Competition_between_colleagues",
                                     "Necessity_of_acquiring_funding", "The_pressure_to_publish", "Funding_opportunities",
                                     "Cooperation_with_industry", "Difficulty_of_appointment_to_post-doc_positions",
                                     "Reliability_of_the_scientific_results")),width =3),
                     
                     box(
                       selectInput("features3_field3", "Third dimension Z:",
                                   c("Research_is_internationally",
                                     "Influence_of_academic_policy", "Requirements_generated_by_evaluations",
                                     "Effort_for_funding_applying", "Competition_between_colleagues",
                                     "Necessity_of_acquiring_funding", "The_pressure_to_publish", "Funding_opportunities",
                                     "Cooperation_with_industry", "Difficulty_of_appointment_to_post-doc_positions",
                                     "Reliability_of_the_scientific_results")),width =3),
                     box(uiOutput("plot_field3"), width = 7)),
   tabItem("field4",
           box(
             selectInput("plot_type4", "Plot type:",
                         c("Barplot", "2D Scatterplot", "3D Bubbleplot")),width =3),
           
           box(
             selectInput("features1_field4", "First dimension X:",
                         c("Research_is_internationally",
                           "Influence_of_academic_policy", "Requirements_generated_by_evaluations",
                           "Effort_for_funding_applying", "Competition_between_colleagues",
                           "Necessity_of_acquiring_funding", "The_pressure_to_publish", "Funding_opportunities",
                           "Cooperation_with_industry", "Difficulty_of_appointment_to_post-doc_positions",
                           "Reliability_of_the_scientific_results")),width =3),
           box(
             selectInput("features2_field4", "Second dimension Y:",
                         c("Research_is_internationally",
                           "Influence_of_academic_policy", "Requirements_generated_by_evaluations",
                           "Effort_for_funding_applying", "Competition_between_colleagues",
                           "Necessity_of_acquiring_funding", "The_pressure_to_publish", "Funding_opportunities",
                           "Cooperation_with_industry", "Difficulty_of_appointment_to_post-doc_positions",
                           "Reliability_of_the_scientific_results")),width =3),
           
           box(
             selectInput("features3_field4", "Third dimension Z:",
                         c("Research_is_internationally",
                           "Influence_of_academic_policy", "Requirements_generated_by_evaluations",
                           "Effort_for_funding_applying", "Competition_between_colleagues",
                           "Necessity_of_acquiring_funding", "The_pressure_to_publish", "Funding_opportunities",
                           "Cooperation_with_industry", "Difficulty_of_appointment_to_post-doc_positions",
                           "Reliability_of_the_scientific_results")),width =3),
           box(uiOutput("plot_field4"), width = 7)),
   tabItem("field5",
           box(
             selectInput("plot_type5", "Plot type:",
                         c("Barplot", "2D Scatterplot", "3D Bubbleplot")),width =3),
           
           box(
             selectInput("features1_field5", "First dimension X:",
                         c("Research_is_internationally",
                           "Influence_of_academic_policy", "Requirements_generated_by_evaluations",
                           "Effort_for_funding_applying", "Competition_between_colleagues",
                           "Necessity_of_acquiring_funding", "The_pressure_to_publish", "Funding_opportunities",
                           "Cooperation_with_industry", "Difficulty_of_appointment_to_post-doc_positions",
                           "Reliability_of_the_scientific_results")),width =3),
           box(
             selectInput("features2_field5", "Second dimension Y:",
                         c("Research_is_internationally",
                           "Influence_of_academic_policy", "Requirements_generated_by_evaluations",
                           "Effort_for_funding_applying", "Competition_between_colleagues",
                           "Necessity_of_acquiring_funding", "The_pressure_to_publish", "Funding_opportunities",
                           "Cooperation_with_industry", "Difficulty_of_appointment_to_post-doc_positions",
                           "Reliability_of_the_scientific_results")),width =3),
           
           box(
             selectInput("features3_field5", "Third dimension Z:",
                         c("Research_is_internationally",
                           "Influence_of_academic_policy", "Requirements_generated_by_evaluations",
                           "Effort_for_funding_applying", "Competition_between_colleagues",
                           "Necessity_of_acquiring_funding", "The_pressure_to_publish", "Funding_opportunities",
                           "Cooperation_with_industry", "Difficulty_of_appointment_to_post-doc_positions",
                           "Reliability_of_the_scientific_results")),width =3),
           box(uiOutput("plot_field5"), width = 7))
      )   
    )
  )
  
# create server function
 server <- function(input, output, session){
#Output data  
    output$data_output <- renderDataTable(data,options = list(
     pageLength = 10, autoWidth = TRUE,
     scrollX = TRUE
   ))
   
# Output all Fields  
   output$fa_block <- renderPlot({
     ggplot(data,aes(Research_field,.data[[input$features]], fill = Answer_category))+
       geom_bar(stat="identity",position="dodge") +
       scale_y_continuous( "Proportion, %", breaks = seq(0, 60, 10))+
       expand_limits(y=c(0,60))+
       labs(x = "Field", y = "Proportion, %", title = " ")+
       theme_minimal() +
       theme(axis.text.x = element_text(angle = 0, hjust = 1, size =14),
             axis.text.y = element_text(size = 14), 
             axis.title.x = element_text(size =18),
             axis.title.y = element_text(size =18),
             legend.title = element_text(size = 16),
             legend.text = element_text(size = 16),
             legend.position = "top") +
     scale_x_discrete (labels = c("Humanities", "Social Sciences","Life Sciences","Natural Sciences","Engineering"))+
     scale_fill_manual(values=DZHWpalette,
                       labels = c("a - far too low", "b - too law","c - appropriate","d - too high","e - far too high"),
                         guide = guide_legend(title = "Answer category"))
  })

# Output Field 1   
   output$plot_field1 <- renderUI({
     if(input$plot_type=="2D Scatterplot"){
     output$plot1_field1 <- renderPlot({
       ggplot(data_field1, aes(x=data_field1[[input$features1_field1]], y=data_field1[[input$features2_field1]], fill = Answer_category, color=Answer_category)) +
       geom_point(size=10)+
       scale_x_continuous("First dimension X, %", breaks = seq(0, 60, 10))+
       expand_limits(x=c(0,60))+
       scale_y_continuous( "Second dimension Y, %", breaks = seq(0, 60, 10))+
       expand_limits(y=c(0,60))+
       theme_minimal() +
       theme(axis.text.x = element_text(size =14),
             axis.text.y = element_text(size = 14), 
             axis.title.x = element_text(size =18),
             axis.title.y = element_text(size =18),
             legend.title = element_text(size = 16),
             legend.text = element_text(size = 16)) +
      scale_color_manual(values=DZHWpalette,
                          c("a - far too low", "b - too law","c - appropriate","d - too high","e - far too high"),
                          guide = guide_legend(title = "Answer category"))+
       scale_fill_discrete(name = " ", breaks=c("none"), labels=c("none"))
   })
     plotOutput("plot1_field1")
     }
     else if (input$plot_type=="Barplot"){
       output$plot2_field1<-renderPlot({
         ggplot(data_field1_long, aes(x=value, y=variable, fill=Answer_category))  +
           geom_col(aes())+
           labs(x = "Proportion, %", y= "Dimensions", title = " ")+
           theme_minimal() +
           theme(axis.text.x = element_text(size =14),
                 axis.text.y = element_text(size = 12), 
                 axis.title.x = element_text(size =18),
                 axis.title.y = element_text(size =18),
                 legend.title = element_text(size = 16),
                 legend.text = element_text(size = 16),
                 legend.position = "bottom") +
                    scale_fill_manual(values=DZHWpalette,
                             c("a - far too low", "b - too law","c - appropriate","d - too high","e - far too high"),
                             guide = guide_legend(title = "Answer category")) 
       
       
     })
       plotOutput("plot2_field1")
     }
     
     else if (input$plot_type=="3D Bubbleplot"){
       output$plot3_field1<-renderPlotly({
         plot3_field1<-plot_ly(
           data_field1,
           x = ~data_field1[[input$features1_field1]], 
           y = ~data_field1[[input$features2_field1]],
           z = ~data_field1[[input$features3_field1]],
           color = ~Answer_category,
           colors= DZHWpalette,
           size = ~data_field1[[input$features1_field1]]+data_field1[[input$features2_field1]]+data_field1[[input$features3_field1]], 
           sizes = c(100, 3000),
           type = "scatter3d",
           mode = "markers",
           marker = list(line = list(width = 2)),
           text =  ~Answer_category,
           textposition = "middle center"
        ) %>%
           layout(
           scene = list(
             xaxis = list(title = "X", range = list(0, 60)),
             yaxis = list(title = "Y", range = list(0, 60)),
             zaxis = list(title = "Z", range = list(0, 60))
             )
           ) 
       })
       plotlyOutput("plot3_field1")
     }    
     
     })
   
 # Output Field2  
   output$plot_field2 <- renderUI({
     if(input$plot_type2=="2D Scatterplot"){
       output$plot1_field2 <- renderPlot({
         ggplot(data_field2, aes(x=data_field2[[input$features1_field2]], y=data_field2[[input$features2_field2]], fill = Answer_category, color=Answer_category)) +
           geom_point(size=10)+
           scale_x_continuous("First dimension X, %", breaks = seq(0, 60, 10))+
           expand_limits(x=c(0,60))+
           scale_y_continuous( "Second dimension Y, %", breaks = seq(0, 60, 10))+
           expand_limits(y=c(0,60))+
           theme_minimal() +
           theme(axis.text.x = element_text(size =14),
                 axis.text.y = element_text(size = 14), 
                 axis.title.x = element_text(size =18),
                 axis.title.y = element_text(size =18),
                 legend.title = element_text(size = 16),
                 legend.text = element_text(size = 16)) +
           scale_color_manual(values=DZHWpalette,
                              c("a - far too low", "b - too law","c - appropriate","d - too high","e - far too high"),
                              guide = guide_legend(title = "Answer category"))+
           scale_fill_discrete(name = " ", breaks=c("none"), labels=c("none"))
       })
       plotOutput("plot1_field2")
     }
     else if (input$plot_type2=="Barplot"){
       output$plot2_field2<-renderPlot({
         ggplot(data_field2_long, aes(x=value, y=variable, fill=Answer_category))  +
           geom_col(aes())+
           labs(x = "Proportion, %", y= "Dimensions", title = " ")+
           theme_minimal() +
           theme(axis.text.x = element_text(size =14),
                 axis.text.y = element_text(size = 12), 
                 axis.title.x = element_text(size =18),
                 axis.title.y = element_text(size =18),
                 legend.title = element_text(size = 16),
                 legend.text = element_text(size = 16),
                 legend.position = "bottom") +
           scale_fill_manual(values=DZHWpalette,
                             c("a - far too low", "b - too law","c - appropriate","d - too high","e - far too high"),
                             guide = guide_legend(title = "Answer category")) 
         
         
       })
       plotOutput("plot2_field2")
     }
     
     else if (input$plot_type2=="3D Bubbleplot"){
       output$plot3_field2<-renderPlotly({
         plot3_field2<-plot_ly(
           data_field2,
           x = ~data_field2[[input$features1_field2]], 
           y = ~data_field2[[input$features2_field2]],
           z = ~data_field2[[input$features3_field2]],
           color = ~Answer_category,
           colors= DZHWpalette,
           size = ~data_field2[[input$features1_field2]]+data_field2[[input$features2_field2]]+data_field2[[input$features3_field2]], 
           sizes = c(100, 3000),
           type = "scatter3d",
           mode = "markers",
           marker = list(line = list(width = 2)),
           text =  ~Answer_category,
           textposition = "middle center"
         ) %>%
           layout(
             scene = list(
               xaxis = list(title = "X", range = list(0, 60)),
               yaxis = list(title = "Y", range = list(0, 60)),
               zaxis = list(title = "Z", range = list(0, 60))
             )
           ) 
       })
       plotlyOutput("plot3_field2")
     }    
     
   })
   
   
 # Output Field3
   output$plot_field3 <- renderUI({
     if(input$plot_type3=="2D Scatterplot"){
       output$plot1_field3 <- renderPlot({
         ggplot(data_field3, aes(x=data_field3[[input$features1_field3]], y=data_field3[[input$features2_field3]], fill = Answer_category, color=Answer_category)) +
           geom_point(size=10)+
           scale_x_continuous("First dimension X, %", breaks = seq(0, 60, 10))+
           expand_limits(x=c(0,60))+
           scale_y_continuous( "Second dimension Y, %", breaks = seq(0, 60, 10))+
           expand_limits(y=c(0,60))+
           theme_minimal() +
           theme(axis.text.x = element_text(size =14),
                 axis.text.y = element_text(size = 14), 
                 axis.title.x = element_text(size =18),
                 axis.title.y = element_text(size =18),
                 legend.title = element_text(size = 16),
                 legend.text = element_text(size = 16)) +
           scale_color_manual(values=DZHWpalette,
                              c("a - far too low", "b - too law","c - appropriate","d - too high","e - far too high"),
                              guide = guide_legend(title = "Answer category"))+
           scale_fill_discrete(name = " ", breaks=c("none"), labels=c("none"))
       })
       plotOutput("plot1_field3")
     }
     else if (input$plot_type3=="Barplot"){
       output$plot2_field3<-renderPlot({
         ggplot(data_field3_long, aes(x=value, y=variable, fill=Answer_category))  +
           geom_col(aes())+
           labs(x = "Proportion, %", y= "Dimensions", title = " ")+
           theme_minimal() +
           theme(axis.text.x = element_text(size =14),
                 axis.text.y = element_text(size = 12), 
                 axis.title.x = element_text(size =18),
                 axis.title.y = element_text(size =18),
                 legend.title = element_text(size = 16),
                 legend.text = element_text(size = 16),
                 legend.position = "bottom") +
           scale_fill_manual(values=DZHWpalette,
                             c("a - far too low", "b - too law","c - appropriate","d - too high","e - far too high"),
                             guide = guide_legend(title = "Answer category")) 
         
         
       })
       plotOutput("plot2_field3")
     }
     
     else if (input$plot_type3=="3D Bubbleplot"){
       output$plot3_field3<-renderPlotly({
         plot3_field3<-plot_ly(
           data_field3,
           x = ~data_field3[[input$features1_field3]], 
           y = ~data_field3[[input$features2_field3]],
           z = ~data_field3[[input$features3_field3]],
           color = ~Answer_category,
           colors= DZHWpalette,
           size = ~data_field3[[input$features1_field3]]+data_field3[[input$features2_field3]]+data_field3[[input$features3_field3]], 
           sizes = c(100, 3000),
           type = "scatter3d",
           mode = "markers",
           marker = list(line = list(width = 2)),
           text =  ~Answer_category,
           textposition = "middle center"
         ) %>%
           layout(
             scene = list(
               xaxis = list(title = "X", range = list(0, 60)),
               yaxis = list(title = "Y", range = list(0, 60)),
               zaxis = list(title = "Z", range = list(0, 60))
             )
           ) 
       })
       plotlyOutput("plot3_field3")
     }    
     
   }) 
   
   
 # Output Field4
   output$plot_field4 <- renderUI({
     if(input$plot_type4=="2D Scatterplot"){
       output$plot1_field4 <- renderPlot({
         ggplot(data_field4, aes(x=data_field4[[input$features1_field4]], y=data_field4[[input$features2_field4]], fill = Answer_category, color=Answer_category)) +
           geom_point(size=10)+
           scale_x_continuous("First dimension X, %", breaks = seq(0, 60, 10))+
           expand_limits(x=c(0,60))+
           scale_y_continuous( "Second dimension Y, %", breaks = seq(0, 60, 10))+
           expand_limits(y=c(0,60))+
           theme_minimal() +
           theme(axis.text.x = element_text(size =14),
                 axis.text.y = element_text(size = 14), 
                 axis.title.x = element_text(size =18),
                 axis.title.y = element_text(size =18),
                 legend.title = element_text(size = 16),
                 legend.text = element_text(size = 16)) +
           scale_color_manual(values=DZHWpalette,
                              c("a - far too low", "b - too law","c - appropriate","d - too high","e - far too high"),
                              guide = guide_legend(title = "Answer category"))+
           scale_fill_discrete(name = " ", breaks=c("none"), labels=c("none"))
       })
       plotOutput("plot1_field4")
     }
     else if (input$plot_type4=="Barplot"){
       output$plot2_field4<-renderPlot({
         ggplot(data_field4_long, aes(x=value, y=variable, fill=Answer_category))  +
           geom_col(aes())+
           labs(x = "Proportion, %", y= "Dimensions", title = " ")+
           theme_minimal() +
           theme(axis.text.x = element_text(size =14),
                 axis.text.y = element_text(size = 12), 
                 axis.title.x = element_text(size =18),
                 axis.title.y = element_text(size =18),
                 legend.title = element_text(size = 16),
                 legend.text = element_text(size = 16),
                 legend.position = "bottom") +
           scale_fill_manual(values=DZHWpalette,
                             c("a - far too low", "b - too law","c - appropriate","d - too high","e - far too high"),
                             guide = guide_legend(title = "Answer category")) 
         
         
       })
       plotOutput("plot2_field4")
     }
     
     else if (input$plot_type4=="3D Bubbleplot"){
       output$plot3_field4<-renderPlotly({
         plot3_field4<-plot_ly(
           data_field4,
           x = ~data_field4[[input$features1_field4]], 
           y = ~data_field4[[input$features2_field4]],
           z = ~data_field4[[input$features3_field4]],
           color = ~Answer_category,
           colors= DZHWpalette,
           size = ~data_field4[[input$features1_field4]]+data_field4[[input$features2_field4]]+data_field4[[input$features3_field4]], 
           sizes = c(100, 3000),
           type = "scatter3d",
           mode = "markers",
           marker = list(line = list(width = 2)),
           text =  ~Answer_category,
           textposition = "middle center"
         ) %>%
           layout(
             scene = list(
               xaxis = list(title = "X", range = list(0, 60)),
               yaxis = list(title = "Y", range = list(0, 60)),
               zaxis = list(title = "Z", range = list(0, 60))
             )
           ) 
       })
       plotlyOutput("plot3_field4")
     }    
     
   }) 
  
    
 # Output Field5
   output$plot_field5 <- renderUI({
     if(input$plot_type5=="2D Scatterplot"){
       output$plot1_field5 <- renderPlot({
         ggplot(data_field5, aes(x=data_field5[[input$features1_field5]], y=data_field5[[input$features2_field5]], fill = Answer_category, color=Answer_category)) +
           geom_point(size=10)+
           scale_x_continuous("First dimension X, %", breaks = seq(0, 60, 10))+
           expand_limits(x=c(0,60))+
           scale_y_continuous( "Second dimension Y, %", breaks = seq(0, 60, 10))+
           expand_limits(y=c(0,60))+
           theme_minimal() +
           theme(axis.text.x = element_text(size =14),
                 axis.text.y = element_text(size = 14), 
                 axis.title.x = element_text(size =18),
                 axis.title.y = element_text(size =18),
                 legend.title = element_text(size = 16),
                 legend.text = element_text(size = 16)) +
           scale_color_manual(values=DZHWpalette,
                              c("a - far too low", "b - too law","c - appropriate","d - too high","e - far too high"),
                              guide = guide_legend(title = "Answer category"))+
           scale_fill_discrete(name = " ", breaks=c("none"), labels=c("none"))
       })
       plotOutput("plot1_field5")
     }
     else if (input$plot_type5=="Barplot"){
       output$plot2_field5<-renderPlot({
         ggplot(data_field5_long, aes(x=value, y=variable, fill=Answer_category))  +
           geom_col(aes())+
           labs(x = "Proportion, %", y= "Dimensions", title = " ")+
           theme_minimal() +
           theme(axis.text.x = element_text(size =14),
                 axis.text.y = element_text(size = 12), 
                 axis.title.x = element_text(size =18),
                 axis.title.y = element_text(size =18),
                 legend.title = element_text(size = 16),
                 legend.text = element_text(size = 16),
                 legend.position = "bottom") +
           scale_fill_manual(values=DZHWpalette,
                             c("a - far too low", "b - too law","c - appropriate","d - too high","e - far too high"),
                             guide = guide_legend(title = "Answer category")) 
         
         
       })
       plotOutput("plot2_field5")
     }
     
     else if (input$plot_type5=="3D Bubbleplot"){
       output$plot3_field5<-renderPlotly({
         plot3_field5<-plot_ly(
           data_field5,
           x = ~data_field5[[input$features1_field5]], 
           y = ~data_field5[[input$features2_field5]],
           z = ~data_field5[[input$features3_field5]],
           color = ~Answer_category,
           colors= DZHWpalette,
           size = ~data_field5[[input$features1_field5]]+data_field5[[input$features2_field5]]+data_field5[[input$features3_field5]], 
           sizes = c(100, 3000),
           type = "scatter3d",
           mode = "markers",
           marker = list(line = list(width = 2)),
           text =  ~Answer_category,
           textposition = "middle center"
         ) %>%
           layout(
             scene = list(
               xaxis = list(title = "X", range = list(0, 60)),
               yaxis = list(title = "Y", range = list(0, 60)),
               zaxis = list(title = "Z", range = list(0, 60))
             )
           ) 
       })
       plotlyOutput("plot3_field5")
     }    
     
   }) 
    
}

# call dashboard
shinyApp(ui=ui, server=server)